.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BERRY" "1" "August 2018" "" ""
.
.SH "NAME"
\fBberry\fR \- floating window manager
.
.SH "SYNOPSIS"
\fBberry\fR [\-hv] [\-c autostart_path]
.
.SH "DESCRIPTION"
A healthy, bite\-sized window manager for XOrg
.
.SH "COMMANDS"
.
.nf

* berry \-h
    print a help message

* berry \-v
    display the current version

* berry \-c /PATH/TO/autostart
    use a custom autostart script (defaults to $XDG_CONFIG_HOME/berry/autostart and then $HOME/\.config/berry/autostart)
.
.fi

