.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "BERRYC" "1" "March 2020" "" ""
.
.SH "NAME"
\fBberryc\fR \- client for berry window manager
.
.SH "SYNOPSIS"
\fBberryc\fR [\-hv] \fIcommand\fR [\fIargs\fR\.\.\.]
.
.SH "DESCRIPTION"
Simple command\-line client to send events to the berry window manager
.
.SH "COMMANDS"
.
.TP
\fBwindow_move\fR \fBx y\fR
Shift the current window by the given x/y coordinates
.
.TP
\fBwindow_move_absolute\fR \fBx y\fR
Move the current window to the absolute x/y coordinates
.
.TP
\fBwindow_resize\fR \fBw h\fR
Shrink or grow the current window by the given w/h arguments
.
.TP
\fBwindow_resize_absolute\fR \fBw h\fR
Resize the current window the absolute w/h arguments
.
.TP
\fBwindow_raise\fR
Raises the current window to the stop of the stack
.
.TP
\fBwindow_monocle\fR
Monocles the curent window, respecting values of TOP_GAP
.
.TP
\fBwindow_close\fR
Closes the current window, in turn terminating the associated process
.
.TP
\fBwindow_center\fR
Centers the current window.
.
.TP
\fBswitch_workspace\fR \fBi\fR
Switch to the given workspace, showing all windows on the new workspace and hiding all windows not on the given workspace
.
.TP
\fBsend_to_workspace\fR \fBi\fR
Send the current window to the specified workspace\. Does not switch workspaces\.
.
.TP
\fBfullscreen\fR
Toggle the fullscreen status of the active window
.
.TP
\fBfullscreen_state\fR
Toggle the fullscreen status of the active window, don't change the size
.
.TP
\fBsnap_left\fR
Move and resize the current window to fill the left half of the screen\. Respects TOP_GAP\.
.
.TP
\fBsnap_right\fR
Move and resize the current window to fill the right half of the screen\. Respects TOP_GAP\.
.
.TP
\fBcardinal_focus\fR \fB1, 2, 3, 4\fR
Switch focus to the nearest window in the specified direction\.
.
.TP
\fBcycle_focus\fR
Switch focus to the next window in the list\.
.

.TP
\fBpointer_focus\fR
Focus the window underneath the pointer\.
.
.TP
\fBfocus_color\fR \fBXXXXXX\fR
Set the color of the outer border for the currently focused window
.
.TP
\fBunfocus_color\fR \fBXXXXXX\fR
Set the color of the outer border for all windows not currently focused
.
.TP
\fBinner_focus_color\fR \fBXXXXXX\fR
Set the color of the inner border for the currently focused window
.
.TP
\fBtext_focus_color\fR \fBXXXXXX\fR
Set the color of title bar text for the focused window
.
.TP
\fBtext_unfocus_color\fR \fBXXXXXX\fR
Set the color of title bar text for all unfocused windows
.
.TP
\fBinner_unfocus_color\fR \fBXXXXXX\fR
Set the color of the inner border for all windows not currently focused
.
.TP
\fBborder_width\fR \fBw\fR
Set the width of the outer border in pixels
.
.TP
\fBinner_border_width\fR \fBw\fR
Set the width of the inner border in pixels
.
.TP
\fBtitle_height\fR \fBh\fR
Set the height of the title bar in pixels
.
.TP
\fBsave_monitor\fR \fBi j\fR
Associate the ith workspace to the jth monitor
.

.TP
\fBsmart_place\fR \fBtrue/false\fR
Place newly created windows in unoccupied regions of the screen.
Otherwise place new clients in the top left corner of the active workspace.
.
.TP
\fBdraw_text\fR \fBtrue/false\fR
determine whether or not to draw text in window title bars
.
.TP
\fBset_font\fR \fBfont_name\fR
Set the name of the font to use (e.g. set_font dina-9)
.
.TP
\fBjson_status\fR \fBtrue/false\fR
determine whether or not BERRY_WINDOW_STATUS reports state in JSON format
or plain text.
.
.TP
\fBname_desktop\fR \fBi\fR \fBd_name\fR
name the ith desktop d_name (Used with _NET_DESKTOP_NAMES)
.
.TP
\fB[manage|unmanage]\fR [Dialog|Toolbar|Menu|Splash|Utility]\fR
Manage, or unmanage, windows of type Dialog, Toolbar, Menu, Splash, or Utility.
By default, Only Toolbars and Splashes are not managed.
.
.TP
\fBedge_gap\fR \fBtop\fR \fBbottom\fR \fBleft\fR \fBright\fR
Set the edge padding around the screen (must include all params)
.
.TP
\fBdecorate_new\fR \fBtrue/false\fR
Determine whether new windows are decorated by default.
.
.TP
\fBmove_button\fR \fB1-5\fR
Determine the button used to move windows using the mouse.
.
.TP
\fBmove_mask\fR \fBmod1/mod2/mod3/mod4/mod5\fR
Determine the key mask used to move windows using the mouse.
.
.TP
\fBresize_button\fR \fB1-5\fR
Determine the button used to resize windows using the mouse.
.
.TP
\fBresize_mask\fR \fBmod1/mod2/mod3/mod4/mod5\fR
Determine the key mask used to resize windows using the mouse.
.
.TP
\fBpointer_interval\fR \fBn\fR
Set the minimum interval for processing motion events to n.
Set to a default value of 0.
Useful for input lag on high refresh rate screens.
If you experience input lag on high refresh rate screens, try a value around 15.
.
.TP
\fBquit\fR \fB\fR
stop the program.
.
.TP
\fBedge_lock\fR \fBtrue/false\fR
Bound windows to the edges of the monitor.
.
.TP
\fBtoggle_decorations\fR
Toggle decorations for the currently focused client
.
.TP
\fBfocus_follows_pointer\fR \fBtrue/false\fR
Focus the window underneath the pointer.
