#ifndef _BERRY_CONFIG_H_
#define _BERRY_CONFIG_H_

#define WORKSPACE_NUMBER 10

#define BORDER_WIDTH 3
#define INTERNAL_BORDER_WIDTH 3
#define TITLE_HEIGHT 30

#define MOVE_STEP 40
#define RESIZE_STEP 40

#define TOP_GAP 30

#define BORDER_UNFOCUS_COLOR 0x20292d
#define BORDER_FOCUS_COLOR 0x20292d

#define INNER_UNFOCUS_COLOR 0x2c3539
#define INNER_FOCUS_COLOR 0xac8d6e

#define TEXT_FOCUS_COLOR 0xeeffff
#define TEXT_UNFOCUS_COLOR 0x546e7a

#define FOCUS_NEW true
#define EDGE_LOCK true
#define TITLE_CENTER true

#endif
